// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1w2tg7VrqjPcsQvn5LKKxWIOb5SQAa0E',
    appId: '1:778896808785:web:c9a7671e53d6e1a37e1170',
    messagingSenderId: '778896808785',
    projectId: 'notes-app-with-ai-example',
    authDomain: 'notes-app-with-ai-example.firebaseapp.com',
    storageBucket: 'notes-app-with-ai-example.appspot.com',
    measurementId: 'G-8VBSMT5ESE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZWSvIpxWbXNAAMD1sSLrC28ffBxbzGbw',
    appId: '1:778896808785:android:b630fd71bbf310017e1170',
    messagingSenderId: '778896808785',
    projectId: 'notes-app-with-ai-example',
    storageBucket: 'notes-app-with-ai-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCawUg2MV6N2L07eCLDyOwpW1pY23_-Xh8',
    appId: '1:778896808785:ios:ed45724e724bdc0d7e1170',
    messagingSenderId: '778896808785',
    projectId: 'notes-app-with-ai-example',
    storageBucket: 'notes-app-with-ai-example.appspot.com',
    iosBundleId: 'com.example.notesAppWithAi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCawUg2MV6N2L07eCLDyOwpW1pY23_-Xh8',
    appId: '1:778896808785:ios:bdc442880bb3c42d7e1170',
    messagingSenderId: '778896808785',
    projectId: 'notes-app-with-ai-example',
    storageBucket: 'notes-app-with-ai-example.appspot.com',
    iosBundleId: 'com.example.notesAppWithAi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1w2tg7VrqjPcsQvn5LKKxWIOb5SQAa0E',
    appId: '1:778896808785:web:c5e7418af64ec5d67e1170',
    messagingSenderId: '778896808785',
    projectId: 'notes-app-with-ai-example',
    authDomain: 'notes-app-with-ai-example.firebaseapp.com',
    storageBucket: 'notes-app-with-ai-example.appspot.com',
    measurementId: 'G-K49B50WFY9',
  );
}