name: notes_app_with_ai
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependency_overrides:
  analyzer: ^6.7.0 # isar required

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  get_it: ^8.0.0
  injectable: ^2.5.0
  auto_route: ^9.2.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.2 
  dio: ^5.7.0
  package_info_plus: ^8.0.3
  rxdart: ^0.28.0
  logging: ^1.2.0
  fancy_logger: ^0.1.5
  surf_lint_rules: ^1.0.0
  easy_logger: ^0.0.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cloud_firestore: ^5.4.4
  another_audio_recorder: ^1.2.1
  just_audio: ^0.9.42


dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  isar_generator: ^3.1.0+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/
